NBCampFinal5/FinalTodo

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Scenes/MainPageScene/FolderDialogViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewController.swift
1. MainPage UI FAB/TableView/NavBar 추가
2. 폴더 추가 Dialog 추가
3. 폴더 수정 기능 추가
> [FEAT]: MainPage UI / Folder Add Dialog 추가

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
1. MemoListView UI 추가
2. MainPage에서 Cell 클릭 시 MemoListView 이동 기능 추가
> [FEAT]: MemoListView UI 추가

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageView.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewController.swift
1. MainPage MVC패턴으로 코드 분리
2. MainPageVC 코드 리팩토링
> [REFACTOR]: MainPage Refactoring

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Scenes/SettingPageScene/SettingCell.swift
- FinalTodo/FinalTodo/Scenes/SettingPageScene/SettingOptionManager.swift
- FinalTodo/FinalTodo/Scenes/SettingPageScene/SettingPageViewController.swift
> [FEAT] 세팅화면 데이터매니저 파일 및 셀 악세사리(>) 코드 추가

- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageView.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewController.swift
1. MainPage tableView, fab, navBar, tabBar, statusBar ColorManager 적용
> [FEAT]: MainPage color theme 적용

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Resource/SceneDelegate.swift
- FinalTodo/FinalTodo/Scenes/PwFindScene/PwFindPageViewController.swift
> [feat]비밀번호찾기 페이지 생성

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageView.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListView.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
[REFACTOR]: MemoList View VC 분리 및 MVC 적용
> [REFACTOR]: MemoList View VC 분리 및 MVC 적용

- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListView.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
1. MemoListView Color Theme 적용
2. memo 사이 구분선 추가
3. memo items 간격 조정
> [FEAT]: MemoListView Color Theme 적용

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Helper/LoginManager.swift
> [FEAT] LoginManager Add

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Scenes/AddMemoPageScene/AddMemoPageViewModel.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
[FEAT]: MainPage MemoListPage FAB 연동
> [FEAT]: MainPage MemoListPage FAB 연동

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Helper/LocationTrackingManager.swift
- FinalTodo/FinalTodo/Helper/MapKitManager.swift
1. moveToLocation(latitude:longitude:):
위도/경도로 지도 표시 - 사용자 현재 장소 지도 표시 기능에 사용
2. searchForLocation(searchText:completion:):
텍스트 입력값 기반 장소를 검색. 검색이 완료 후 좌표를 반환
> [FEAT]: MapKitManger 추가

- FinalTodo/FinalTodo/Helper/FirebaseManager.swift
> [FEAT] 오류 해결

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Scenes/AddMemoNotifySettingScene/DateSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddMemoNotifySettingScene/LocationSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddMemoNotifySettingScene/NotifySettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddMemoPageScene/AddMemoPageViewModel.swift
- FinalTodo/FinalTodo/SharedView/Cells/MemoOptionCollectionViewCell.swift
1. DateSettingPageViewController 추가
- 현재 날짜로 pickerView 생성, 설정완료 시 날짜 설정 색상 변화
2. NotifySettingPageViewController 수정
-  설정완료 시 날짜 설정 색상 변화
#67
> [FEAT]: 날짜 시간 위치 설정 각각의 뷰 분리 및 날짜 시간 설정 뷰 작업

- FinalTodo/FinalTodo/Scenes/LockScreenScene/LockScreenViewController.swift
- FinalTodo/FinalTodo/Scenes/LockScreenScene/LockScreenViewModel.swift
[FEAT] 비밀번호 틀릴 때 UI구현 (UIView shake)
> [FEAT] 비밀번호 틀릴 때 UI구현 (UIView shake)

- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/NotifyScene/NotifyPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingOption.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingOptionManager.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingPageViewController.swift
- FinalTodo/FinalTodo/SharedView/Cells/SettingCell.swift
[FEAT]: SettingOption switch Bool 타입으로 수정
> [FEAT]: SettingOption switch Bool 타입으로 수정

- FinalTodo/FinalTodo/Model/Managers/MapKitManager.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/LocationSettingViewController.swift
1. LocationSettingVC에 MapKitManager 연동
2. LocationSettingVC에 현재 사용자 위치 지도에 표시하는 기능 추가
3. LocationSettingVC에 주소 검색 기능 및 검색 주소 값 저장 기능 추가
4. MapKitManager에 주소값 불러오기 기능 추가 / 초기화 방법 변경
> [FEAT]: LocationSettingView MapKitManager 연동

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Helper/Notifications.swift
- FinalTodo/FinalTodo/Helper/TabBarController.swift
- FinalTodo/FinalTodo/Model/Managers/NotifySettingManager.swift
- FinalTodo/FinalTodo/Resource/AppDelegate.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/DateSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/NotifySettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewModel.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddNotifyScene/AddNotifyPageViewController.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageViewController.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/DdayPageScene/DdayPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/NotifyScene/NotifyPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingOption.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingOptionManager.swift
- FinalTodo/FinalTodo/SharedView/Cells/SettingCell.swift
1. 푸시알림 설정페이지(NotifyPageViewController) 푸시알림 설정 추가
2. 메세지 작성 페이지 내 날짜, 시간 알림 설정 기능 구현
> [FEAT]: 푸시알림 설정페이지(NotifyPageViewController) 푸시알림 설정 추가

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/ProfilePageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/ProfilePageViewModel.swift
> [FEAT] ProfileViewModel 추가

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Helper/Notifications.swift
- FinalTodo/FinalTodo/Model/Managers/NotifySettingManager.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/AddMemoMainNotifyViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/DateSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/NotifySettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/TimeSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/NotifyScene/NotifyPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingOption.swift
- FinalTodo/FinalTodo/SharedView/ButtonTappedView.swift
- FinalTodo/FinalTodo/SharedView/Cells/SettingCell.swift
[FEAT]: 날짜,시간 페이지 분리 및 선택 날짜, 시간에 알림기능 구현
> [FEAT]: 날짜,시간 페이지 분리 및 선택 날짜, 시간에 알림기능 구현

- FinalTodo/FinalTodo/Scenes/LoginScene/SginInScene/SignInPageViewController.swift
> [FIX] 주석처리

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/SearchViewController.swift
- FinalTodo/FinalTodo/SharedView/Cells/MemoTableViewCell.swift
1. MemoCell 분리
2. MainPage SearchButton 기능 추가
3. SearchVC 추가
> [FEAT]: SearchVC 추가

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Model/Managers/FirebaseDBManager.swift
1. 싱글톤패턴으로 파이어베이스 전역관리
2. User데이터 create/update/fetch/delete 기능 구현
3. 인코딩 디코딩 extension 추가
> [FEAT]: Firebase Database Manager 추가

- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/DeleteAccountPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/ProfilePageViewController.swift
> [FIX] 프로필페이지 UI 수정

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewScene/MainPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/SearchViewScene/SearchViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/SearchViewScene/SearchViewModel.swift
> [FEAT] SearchViewController DB연결

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
[FIX] GoogleService파일 삭제!!!!!!!!
> [FIX] GoogleService파일 삭제!!!!!!!!

- FinalTodo/FinalTodo/Helper/Extensions.swift
- FinalTodo/FinalTodo/Helper/LockController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewScene/MainPageView.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewScene/MainPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
- FinalTodo/FinalTodo/Scenes/RewardPageScene/ColorUIViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/LockSettingPageScene/LockSettingScene/LockSettingViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/LockSettingPageScene/LockSettingScene/LockSettingViewModel.swift
- FinalTodo/FinalTodo/SharedView/Cells/LockScreenNumCollectionViewCell.swift
- FinalTodo/FinalTodo/SharedView/Cells/LockScreenPasswordCollectionViewCell.swift
[FEAT] Color 설정 및 LockScreen 기능 버그 수정
> [FEAT] Color 설정 및 LockScreen 기능 버그 수정

- FinalTodo/FinalTodo/Helper/Extensions.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageView.swift
[FIX] Color 초기값 오류 FIX
[APPLY] Color 적용
> [FIX] Color 초기값 오류 FIX

- FinalTodo/FinalTodo/Helper/Extensions.swift
- FinalTodo/FinalTodo/Helper/Protocol.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListView.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
- FinalTodo/FinalTodo/SharedView/Cells/MemoOptionCollectionViewCell.swift
[FEAT]: 메모페이지mypoint 컬러사용, 메모추가화면 내용수정기능 변경
> [FEAT]: 메모페이지mypoint 컬러사용, 메모추가화면 내용수정기능 변경

- FinalTodo/FinalTodo/Scenes/RewardPageScene/ColorUIViewController.swift
- FinalTodo/FinalTodo/Scenes/RewardPageScene/RewardPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/NotifyScene/NotifyPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/DeleteAccountPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/ProfilePageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingPageViewController.swift
- FinalTodo/FinalTodo/SharedView/Cells/SettingCell.swift
- 포인트 컬러 변경 대응
- 다크모드 대응
`.systemBackground .secondarySystemBackground .label`
> [FIX] add PointColor to SettingScenes

- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/ProfilePageViewController.swift
> [FIX] 레이블 텍스트 수정

- FinalTodo/FinalTodo/Helper/TabBarController.swift
[FEAT] TabBarController animation, swipe 기능 구현
> [FEAT] TabBarController animation, swipe 기능 구현

- FinalTodo/FinalTodo/Model/Managers/FirebaseDBManager.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewScene/MainPageViewController.swift
1. MainPage Folder Firebase CRUD 적용
2. AddMemoPage Memo Firebase CRUD 적용
3. FirebaseDBManager Refactoring
> [FEAT]: MainPage/AddMemo Page Firebase CRUD 적용

- FinalTodo/FinalTodo/Model/Managers/FirebaseDBManager.swift
[FIX]: FiresbaseDBManager user관련 함수 이름 수정
- createUserData -> createUser
> [FIX]: FiresbaseDBManager user관련 함수 이름 수정

- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/DdayPageScene/DdayPageViewController.swift
- FinalTodo/FinalTodo/Scenes/LoginScene/SginInScene/SignInPageViewController.swift
- FinalTodo/FinalTodo/Scenes/LoginScene/SignUpScene/SignUpPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/SearchViewScene/SearchViewController.swift
> [FEAT]: 성준  키보드대응

- FinalTodo/FinalTodo/Helper/Extensions.swift
- FinalTodo/FinalTodo/Helper/Notifications.swift
- FinalTodo/FinalTodo/Helper/Protocol.swift
- FinalTodo/FinalTodo/Model/Managers/CoreDataManager.swift
- FinalTodo/FinalTodo/Model/User.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/AddMemoMainNotifyViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/DateSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/TimeSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewModel.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageView.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewModel.swift
- FinalTodo/FinalTodo/SharedView/MemoView.swift
> [FEAT]: 메모별 알림설정

- FinalTodo/FinalTodo/Helper/Extensions.swift
- FinalTodo/FinalTodo/Helper/Notifications.swift
- FinalTodo/FinalTodo/Helper/Protocol.swift
- FinalTodo/FinalTodo/Model/Managers/CoreDataManager.swift
- FinalTodo/FinalTodo/Model/User.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/AddMemoMainNotifyViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/DateSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/TimeSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewModel.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageView.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewModel.swift
- FinalTodo/FinalTodo/Scenes/RewardPageScene/RewardPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/ProfilePageViewModel.swift
- FinalTodo/FinalTodo/SharedView/MemoView.swift
> [FEAT]: 작업전 세팅

- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarListScene/CalendarListViewController.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageViewController.swift
- FinalTodo/FinalTodo/Scenes/RewardPageScene/ColorUIViewController.swift
> [FEAT] 기본컬러 구현

- FinalTodo/FinalTodo/Scenes/LoginScene/SginInScene/SignInPageViewController.swift
- FinalTodo/FinalTodo/Scenes/LoginScene/SignUpScene/SignUpPageViewController.swift
> [FEAT] loginButton color 변경

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Helper/Print.swift
- FinalTodo/FinalTodo/Model/FolderModel+CoreDataProperties.swift
- FinalTodo/FinalTodo/Model/Managers/CoreDataManager.swift
- FinalTodo/FinalTodo/Model/Managers/FirebaseDBManager.swift
- FinalTodo/FinalTodo/Model/Managers/LoginManager.swift
- FinalTodo/FinalTodo/Model/MemoModel+CoreDataProperties.swift
- FinalTodo/FinalTodo/Model/User.swift
- FinalTodo/FinalTodo/Resource/AppDelegate.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewScene/MainPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/DeleteAccountPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingPageViewController.swift
1. FirebaseDBManager Firebase Coredata로 업데이트 메서드 추가
2. 회원탈퇴 시 Firebase 유저 삭제 기능 추가
3. LoginManager에 Firebase Data <> Coredata 연동 기능 추가
4. Background 진입 시 Firebase 업데이트 기능 추가
5. Main, AddMemo Page Firebase 관련 메서드 삭제
6. Logout시 Firebase Coredata기반 업데이트 기능 추가
> [FEAT]: Firebase <> Coredata 업데이트 기능 추가 및 메서드 배치

- FinalTodo/FinalTodo/Resource/AppDelegate.swift
- FinalTodo/FinalTodo/Resource/SceneDelegate.swift
1. AppDelegate > SceneDelegate로 해당 코드 이전
> [FIX]: Background 진입 시 Firebase <> Coredata 패치 기능 코드 수정

- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/DeleteAccountPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/ProfilePageViewController.swift
> [FIX] 디자이너 의견 반영 프로필, 계정삭제 페이지 UI 수정

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Helper/Protocol.swift
- FinalTodo/FinalTodo/Resource/SceneDelegate.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/AddMemoMainNotifyViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewModel.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/SearchViewScene/SearchViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
> [FEAT] 검색결과 UI수정 및 메모작성화면 컬렉션뷰 수정

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Resource/SceneDelegate.swift
> [FEAT]: 검색결과 UI수정 및 메모작성화면 컬렉션뷰 수정 재업

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Resource/SceneDelegate.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/AddMemoMainNotifyViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/DateSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/TimeSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
- 메모추가화면 알림설정 화면에 예약초기화 버튼 추가
- 예약초기화 버튼 터치시 기존 알림 삭제 기능 추가
> [FEAT]: 메모추가화면 알림설정내 예약초기화 기능추가

- FinalTodo/FinalTodo/Model/Managers/LoginManager.swift
- FinalTodo/FinalTodo/Resource/SceneDelegate.swift
- FinalTodo/FinalTodo/Scenes/LoginScene/SginInScene/SignInPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewScene/MainPageViewController.swift
- FinalTodo/FinalTodo/Scenes/RewardPageScene/RewardPageViewController.swift
- FinalTodo/FinalTodo/Scenes/RewardPageScene/RewardPageViewModel.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/LockSettingPageScene/LockPasswordChangeScene/LockPasswordChangeViewController.swift
- FinalTodo/FinalTodo/SharedView/CircularProgressView.swift
- 로그아웃 시점 수정
- 로그인시 인디케이터 추가
- 로그아웃시 유저디폴트값 초기화
- RewardPage UI수정
> [FEAT] 로그아웃 시점 수정 / 로그인시 인디케이터 추가 /로그아웃시 유저디폴트값 초기화 /RewardPage UI수정

- FinalTodo/FinalTodo/Model/User.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/AddMemoMainNotifyViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/DateSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/TimeSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarListScene/CalendarListViewController.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageView.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageViewController.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/DdayPageScene/DdayPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewScene/MainPageView.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
- FinalTodo/FinalTodo/SharedView/ButtonTappedView.swift
- FinalTodo/FinalTodo/SharedView/ModalTopView.swift
> [FEAT]: 캘린더 UI 및 일부 버튼 UI 수정

- FinalTodo/FinalTodo/Resource/AppDelegate.swift
- FinalTodo/FinalTodo/Resource/SceneDelegate.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewScene/MainPageViewController.swift
- FinalTodo/FinalTodo/Scenes/RewardPageScene/RewardPageViewController.swift
De bug/1105 debug
- 로그아웃 시점 변경
- 코드 분리
> De bug/1105 debug

- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/ProfilePageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/ProfilePageViewModel.swift
- 리워드 페이지와 동일한 로직으로 기니프로필 이미지 변경
- 아이디 레이블 추가
- 셀 텍스트 변경: 리워드 네임 변경-> 기니 닉네임 변경
> [FEAT] 프로필 아이디 IU 추가 및 기니 이미지 로직 구현

- FinalTodo/FinalTodo/Scenes/LoginScene/SginInScene/SignInPageViewController.swift
- 기존 아이디 로그아웃 후 다른 아이디 로그인 시 기존 아이디에서 설정한 마이컬러가 보이는 오류를 수정하기 위해, 로그인 시 마이포인트 컬러 재할당 로직 추가
> [FIX] 로그인 시 myPointColor 재할당

- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarListScene/CalendarListViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListView.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/SearchViewScene/SearchViewController.swift
- 메모, 캘린더, 검색 리스트 화면 셀 높이 및 셀 스타일 통일 
- 검색 리스트에 해당하는 화면 연결
> [FIX] 메모, 캘린더, 검색 리스트 셀 수정 및 화면 연결

- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewScene/MainPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingPageViewController.swift
- 최상위페이지를 제외한 하위 페이지에서 탭바 숨기기
- 최상위페이지 뷰 나타날 때 탭바 숨기기 false 처리
> [FIX] 하위페이지 탭바 숨기기

- FinalTodo/FinalTodo/Model/Managers/CoreDataManager.swift
- FinalTodo/FinalTodo/Resource/AppDelegate.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/AddMemoMainNotifyViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/DateSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/LocationSettingViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/TimeSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewScene/MainPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
- FinalTodo/FinalTodo/SharedView/ButtonTappedView.swift
- 로그인버튼, 메모알림설정버튼들 터치 수정
- 폴더 순서 이름순으로 정렬(한글이 영어보다 상단배치)
- 메모목록내 메모들 수정최신순으로 정렬
> [FEAT] 로그인버튼, 메모알림설정버튼들 수정, 폴더 순서 이름순으로 정렬, 메모목록 최신순으로 정렬 추가

- FinalTodo/FinalTodo/Helper/Protocol.swift
- FinalTodo/FinalTodo/Model/Managers/LocationTrackingManager.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/LocationSettingViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewModel.swift
1. geofencing 모니터링 후 알림 기능 추가
2. 위치설정 후 해당 정보 표시 기능 (수정필요)
> [FEAT]: Geofencing 관련 기능 추가

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
재업
- 메인화면 색변경 
- 앱삭제 후 앱실행시 오류해결
> [FEAT]메인화면 색변경 및 앱삭제 후 앱실행시 오류해결 재업

- FinalTodo/FinalTodo/Model/Managers/FirebaseDBManager.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/ProfilePageScene/DeleteAccountPageViewController.swift
1. firebaseDBManager firstore,auth deleteUser 메서드 추가 및 수정
2. DeleteAccountPageVC에 deleteUser 기능 추가 및 적용
> [FEAT]: firestore, authentication deleteUser 기능 추가 및 적용

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Helper/UserDefaultsManager.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingOptionManager.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/privacyPolicyScene/PrivacyPolicyViewController.swift
- FinalTodo/FinalTodo/SharedView/Cells/MemoOptionCollectionViewCell.swift
- 설정탭 내 개인정보처리방침 셀 추가
- 메모 추가 페이지 내 설정시 컬렉션뷰 테두리(border) 삭제
- 메모 추가 페이지 내 컬렉션뷰 터치시 반응 추가
> [FEAT] 설정탭내 개인정보처리방침 추가 및 메모추가페이지 border 기능수정

- FinalTodo/FinalTodo/Model/Managers/MapKitManager.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/LocationSettingViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
1. MapKitManager 핀 표시 및 핀을 통한 위치 설정 기능 추가
2. 위치 설정 페이지에서 핀 기능 적용 및 지도 줌 확대
3. MemoView 상단 설정 위치 표시 추가
4. 현재 위치 지도에서 더 확대해서 표시
> [REFACTOR]: MapKitManager 핀 표시 및 핀을 통한 위치 설정 기능 추가

- FinalTodo/FinalTodo/Helper/UserDefaultsManager.swift
- FinalTodo/FinalTodo/Scenes/LoginScene/SignUpScene/SignUpPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/SearchViewScene/SearchViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/SearchViewScene/SearchViewModel.swift
> [FEAT] 검색 메모순서 최신 수정순으로 정렬

- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageView.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageViewController.swift
> 캘린더페이지 네비게이션바 경계선 삭제

- FinalTodo/FinalTodo/Model/Managers/LocationTrackingManager.swift
- FinalTodo/FinalTodo/Resource/Info.plist
[FIX]: 리젝대응 - 강제 설정 이동 기능 제거 / 위치정보 요청 문구 수정
> [FIX]: 리젝대응 - 강제 설정 이동 기능 제거 / 위치정보 요청 문구 수정

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
> gps 설정알림변경

- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarListScene/CalendarListViewController.swift
- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarPageViewController.swift
- 캘린더 날짜 셀에 해당 날짜 알림이 있는 경우 "." 표기
- 캘린더 날짜 셀 선택 시 해당 날짜 알림메모 창 이동
> 1.1/feat/calendar list

- FinalTodo/FinalTodo/Helper/Protocol.swift
- FinalTodo/FinalTodo/Model/Managers/CoreDataManager.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/AddMemoMainNotifyViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/DateSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/TimeSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MainPageViewScene/MainPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
- FinalTodo/FinalTodo/Scenes/MainPageScene/SearchViewScene/SearchViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
- FinalTodo/FinalTodo/Scenes/SettingScene/SettingPageScene/SettingOption.swift
- 알림설정 컬렉션뷰 배경색 없어지는 버그 수정
- 폴더 삭제 시 주의 알럿 추가
- 메모 검색 화면에서 메모셀 시간 내림차순으로 정렬 안되던 부분 수정
- 알림설정 컬렉션뷰 화면 내 날짜, 시간 셀에 설정한 날짜, 시간 표시 추가
- 알림설정 컬렉션뷰 화면에서 예약초기화 시 알림설정 컬렉션뷰 초기화안되는 부분 수정
- 메모화면 내 알림설정 컬렉션뷰에 설정한 시간 나타는 부분 2023.11.09 오후 1:09 로 수정 -> 오후 12시가 00으로 나타나는 오류 수정
> [FIX] 알림설정 컬렉션뷰 버그 수정 및 폴더 삭제시 알럿 추가

- FinalTodo/FinalTodo/Helper/Protocol.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/AddMemoMainNotifyViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/DateSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoNotifySettingScene/TimeSettingPageViewController.swift
- FinalTodo/FinalTodo/Scenes/AddScene/AddMemoPageScene/AddMemoPageViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
> [FEAT] 설정초기화 버튼 동작시 날짜,시간 셀 초기화

- FinalTodo/FinalTodo/Scenes/CalendarPageScene/CalendarListScene/CalendarListViewController.swift
> [FIX] dismiss 버그 수정

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
> [FIX]  버전 1.1

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Scenes/LoginScene/SignUpScene/SignUpPageView.swift
- FinalTodo/FinalTodo/Scenes/LoginScene/SignUpScene/SignUpPageViewController.swift
- FinalTodo/FinalTodo/Scenes/LoginScene/SignUpScene/SignUpPageViewModel.swift
- 디자인 패턴 적용
- observable class를 이용한 bind 구현
> 1.1.2/refactor/sign up page scene 디자인 패턴 적용

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
- FinalTodo/FinalTodo/Helper/Extensions.swift
- FinalTodo/FinalTodo/Helper/TabBarController.swift
- FinalTodo/FinalTodo/Scenes/LoginScene/SginInScene/SignInPageViewController.swift
- FinalTodo/FinalTodo/Scenes/LoginScene/SignUpScene/SignUpPageView.swift
- FinalTodo/FinalTodo/Scenes/LoginScene/SignUpScene/SignUpPageViewController.swift
- FinalTodo/FinalTodo/Scenes/RewardPageScene/RewardPageView.swift
- FinalTodo/FinalTodo/Scenes/RewardPageScene/RewardPageViewController.swift
- rewardPage view 파일 분리
- rewardPage viewModel init으로 외부에서 주입
- rewardPage 디자인 튜터님 피드백적용
- 회원가입 페이지 보기 버튼 색상 변경 -> 다크모드시 안보이는 문제 
- signUpPage viewModel init으로 외부에서 주입
> 1.1.2/refactor/reward page scene

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
> [FEAT] 버전 1.1.2.로 수정

- FinalTodo/FinalTodo/Scenes/MainPageScene/MemoListViewController.swift
- FinalTodo/FinalTodo/Scenes/MemoPageScene/MemoViewController.swift
> [FIX] 알림, 위치설정 오류 수정 버전1.1.2

- FinalTodo/FinalTodo.xcodeproj/project.pbxproj
> [FEAT] 버전 1.1.3 으로 업데이트
